# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
stages:
  - stage: dev
    jobs:
    - job: Job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: CmdLine@2
        displayName: 'Run a one-line script'
        inputs:
          script: echo Hello, world!
      - task: CmdLine@2
        displayName: 'Run a multi-line script'
        inputs:
          script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
  - stage: test
    jobs:
    - job: Job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: CmdLine@2
        displayName: 'Run a one-line script'
        inputs:
          script: echo Hello, world!
      - task: CmdLine@2
        displayName: 'Run a multi-line script'
        inputs:
          script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml            
  - stage: prod
    jobs:
    - job: Job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: CmdLine@2
        displayName: 'Run a one-line script'
        inputs:
          script: echo Hello, world!
      - task: CmdLine@2
        displayName: 'Run a multi-line script'
        inputs:
          script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml            
